package de.linzn.mineGuild.objects;

public enum GuildAction {
    DELETE, DEPOSIT, WITHDRAW, RANGS, HOME, INVITE, KICK, LEAVE, SETGUILDMASTER, SETGUILDNAME, SETHOME, ACCEPT, HELP, INFO, LIST, MEMBERS, CREATE, SETRANG

}
